cp config.ttyACM0 config.ttyACM1
cp config.ttyACM0 config.ttyACM2
cp config.ttyACM0 config.ttyACM3
cp config.ttyACM0 config.ttyACM4
cp config.ttyACM0 config.ttyACM5
cp config.ttyACM0 config.ttyACM6
cp config.ttyACM0 config.ttyACM7
cp config.ttyACM0 config.ttyACM8
cp config.ttyACM0 config.ttyACM9
cp config.ttyACM0 config.ttyACM10
cp config.ttyACM0 config.ttyACM11
cp config.ttyACM0 config.ttyACM12
cp config.ttyACM0 config.ttyACM13
cp config.ttyACM0 config.ttyACM14
cp config.ttyACM0 config.ttyACM15
cp config.ttyACM0 config.ttyACM16
cp config.ttyACM0 config.ttyACM17
